FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["WebApplicationXml/WebApplicationXml.csproj", "WebApplicationXml/"]
RUN dotnet restore "WebApplicationXml.csproj"
COPY . .
WORKDIR "/src/WebApplicationXml"
RUN dotnet build "WebApplicationXml.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApplicationXml.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApplicationXml.dll"]
